@Zhengyan.FSServer_HostAddress = http://192.168.113.94:8083

POST {{Zhengyan.FSServer_HostAddress}}/kbserver/api/v1/Knowledge/AddKnowledge
Content-Type: application/json

{
  "dbName": "string",
  "chunkSize": 0,
  "knowledgeList": [
    {
      "dataType": 1,
      "content": "string",
      "metaData": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      }
    }
  ]
}



###

POST {{Zhengyan.FSServer_HostAddress}}/kbserver/api/v1/Knowledge/QueryKnowledge
Content-Type: application/json

{
  "dbName": "string",
  "topK": 10,
  "queryParamType": 1,
  "queryParam": "string"
}